name: Laravel CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3.6'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Launch Pint inspection
      run: vendor/bin/pint --test
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Dockerize Laravel Application
      run: |
        docker-compose -f docker-compose.ci.yml up -d
        docker-compose -f docker-compose.ci.yml exec -T app php artisan migrate --seed
        docker-compose -f docker-compose.ci.yml exec -T app php artisan test

    # - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: php artisan test
